### ISSUE TITLE
split confusion

### ISSUE THREAD

**Issue by Maxhodges** [martinandert/counterpart#39]
I'm unclear about what the docs are saying about 'splitting'. Can someone explain better? This doesn't seem grammatical to me

> The separator option allows you to change what the key gets split via for nested objects. It also allows you to stop counterpart splitting keys if you have a flat object structure:

**Comment by martinandert** [comment]
Hi Max,

let's assume you have the following translation registered:

```js
{
  en: {
    foo: {
      bar: 'baz'
    }
  }
}
```

As the dot (`.`) is the default separator, you can get the value of the translation by simply calling

```js
translate('foo.bar', { locale: 'en' }) //=> 'baz'
```

If for whatever reason you cannot use the dot character (perhaps because you already use it as part of the individual (sub)keys), you can switch to a different separator character like this:

```js
translate('foo/bar', { locale: 'en', separator: '/' }) //=> 'baz'
```

I hope this answers you question. If not, please let me know!
